### PR TITLE
Build failure fixes and minor cleanups to improve logging

### PR DESCRIPTION
**Pull request by mkvalluri**
There was build failure when I ran this sample. 
So I've fixed that part and also added default.toml file to store the service name. While doing this, also did minor change to code to also log timestamp.

### CODE REVIEW

**Comment by mkvalluri** [comment]
Below is the screenshot of build failure.

image

**Comment by mwrock** [comment]
This looks good! My only suggestion is to use `{{pkg.name}}` instead of `{{cfg.service_name}}` so you can avoid adding the config setting which is likely not to ever change.

**Comment by mkvalluri** [comment]
Yeah, for this example I had to do this because of the package name being different from service name. Should I rename the package name to match the service name?

**Comment by mwrock** [comment]
fair enough!

**Pull request merged**
